USE DATABASE PIPELINE_MONITORING;
USE SCHEMA DQ_PROJECT;

CREATE TABLE IF NOT EXISTS GOLD_DQ_RESULTS (
    TABLE_NAME STRING,
    LOAD_ID STRING,
    RULE_ID STRING,
    RULE_NAME STRING,
    RULE_SCOPE STRING,
    ROWS_CHECKED NUMBER,
    ROWS_FAILED NUMBER,
    FAIL_RATE FLOAT,
    RULE_STATUS STRING,
    CHECK_TIMESTAMP TIMESTAMP
);

CREATE TABLE IF NOT EXISTS GOLD_FRESHNESS (
    TABLE_NAME STRING,
    CHECK_TS TIMESTAMP,
    LAST_BUSINESS_TS TIMESTAMP,
    HOURS_BEHIND FLOAT,
    EXPECTED_INTERVAL_HOURS FLOAT,
    FRESHNESS_STATUS STRING
);
