USE DATABASE PIPELINE_MONITORING;
USE SCHEMA DQ_PROJECT;

-- Load DQ results from the internal stage
COPY INTO GOLD_DQ_RESULTS
FROM @GOLD_STAGE
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
PATTERN = '.*dq.*[.]csv'
ON_ERROR = 'CONTINUE';


-- Load freshness results from the internal stage
COPY INTO GOLD_FRESHNESS
FROM @GOLD_STAGE
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
PATTERN = '.*freshness.*[.]csv'
ON_ERROR = 'CONTINUE';


-- Verify loaded data
SELECT COUNT(*) AS DQ_ROWS
FROM GOLD_DQ_RESULTS;

SELECT COUNT(*) AS FRESHNESS_ROWS
FROM GOLD_FRESHNESS;
