CREATE DATABASE IF NOT EXISTS PIPELINE_MONITORING;
CREATE SCHEMA IF NOT EXISTS PIPELINE_MONITORING.DQ_PROJECT;
CREATE STAGE IF NOT EXISTS PIPELINE_MONITORING.DQ_PROJECT.GOLD_STAGE;
LIST @PIPELINE_MONITORING.DQ_PROJECT.GOLD_STAGE;
CREATE TABLE IF NOT EXISTS PIPELINE_MONITORING.DQ_PROJECT.GOLD_DQ_RESULTS (
    TABLE_NAME STRING,
    LOAD_ID STRING,
    RULE_ID STRING,
    RULE_NAME STRING,
    RULE_SCOPE STRING,
    ROWS_CHECKED NUMBER,
    ROWS_FAILED NUMBER,
    FAIL_RATE FLOAT,
    RULE_STATUS STRING,
    CHECK_TIMESTAMP TIMESTAMP_TZ
);
COPY INTO PIPELINE_MONITORING.DQ_PROJECT.GOLD_DQ_RESULTS
FROM @PIPELINE_MONITORING.DQ_PROJECT.GOLD_STAGE
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT';
SELECT *
FROM PIPELINE_MONITORING.DQ_PROJECT.GOLD_DQ_RESULTS;
COPY INTO PIPELINE_MONITORING.DQ_PROJECT.GOLD_DQ_RESULTS
FROM @PIPELINE_MONITORING.DQ_PROJECT.GOLD_STAGE
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT';
SELECT
    FILE_NAME,
    STATUS,
    ROW_COUNT,
    LAST_LOAD_TIME
FROM TABLE(
    PIPELINE_MONITORING.INFORMATION_SCHEMA.COPY_HISTORY(
        TABLE_NAME => 'DQ_PROJECT.GOLD_DQ_RESULTS',
        START_TIME => DATEADD('hour', -1, CURRENT_TIMESTAMP())
    )
)
ORDER BY LAST_LOAD_TIME DESC;
CREATE TABLE IF NOT EXISTS PIPELINE_MONITORING.DQ_PROJECT.GOLD_FRESHNESS (
    TABLE_NAME STRING,
    CHECK_TS TIMESTAMP_TZ,
    LAST_BUSINESS_TS TIMESTAMP_TZ,
    HOURS_BEHIND FLOAT,
    EXPECTED_INTERVAL_HOURS FLOAT,
    FRESHNESS_STATUS STRING
);
COPY INTO PIPELINE_MONITORING.DQ_PROJECT.GOLD_FRESHNESS
FROM @PIPELINE_MONITORING.DQ_PROJECT.GOLD_STAGE/freshness
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT';
LIST @PIPELINE_MONITORING.DQ_PROJECT.GOLD_STAGE;
LIST @PIPELINE_MONITORING.DQ_PROJECT.GOLD_STAGE;

LIST @PIPELINE_MONITORING.DQ_PROJECT.GOLD_STAGE
PATTERN = '.*7996046933608554371.*';
COPY INTO PIPELINE_MONITORING.DQ_PROJECT.GOLD_FRESHNESS
FROM @PIPELINE_MONITORING.DQ_PROJECT.GOLD_STAGE
FILES = (
    'part-00000-tid-7996046933608554371-f2469ec6-6c34-403f-a9b3-5911df85a528-151-1-c000.csv'
)
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT';SELECT *
FROM PIPELINE_MONITORING.DQ_PROJECT.GOLD_FRESHNESS;
SELECT
    TABLE_NAME,
    LOAD_ID,
    RULE_ID,
    RULE_NAME,
    CHECK_TIMESTAMP::DATE AS CHECK_DAY,
    ROWS_CHECKED,
    ROWS_FAILED,
    FAIL_RATE,
    RULE_STATUS
FROM PIPELINE_MONITORING.DQ_PROJECT.GOLD_DQ_RESULTS
WHERE RULE_SCOPE = 'row'
ORDER BY CHECK_DAY, RULE_ID;
SELECT
    TABLE_NAME,
    CHECK_TS,
    LAST_BUSINESS_TS,
    HOURS_BEHIND,
    EXPECTED_INTERVAL_HOURS,
    FRESHNESS_STATUS
FROM PIPELINE_MONITORING.DQ_PROJECT.GOLD_FRESHNESS;
SELECT
    RULE_ID,
    RULE_NAME,
    SUM(ROWS_FAILED) AS TOTAL_FAILED,
    COUNT_IF(ROWS_FAILED > 0) AS LOADS_FIRED,
    COUNT(*) AS LOADS_CHECKED,
    MAX(ROWS_FAILED) AS WORST_SINGLE_LOAD,
    ROUND(
        MAX(ROWS_FAILED) / NULLIF(SUM(ROWS_FAILED), 0),
        3
    ) AS CONCENTRATION,
    ROUND(
        SUM(ROWS_FAILED) / NULLIF(SUM(ROWS_CHECKED), 0),
        5
    ) AS FAIL_RATE
FROM PIPELINE_MONITORING.DQ_PROJECT.GOLD_DQ_RESULTS
WHERE RULE_SCOPE = 'row'
  AND TABLE_NAME = 'orders'
GROUP BY RULE_ID, RULE_NAME
ORDER BY TOTAL_FAILED DESC;
SELECT COUNT(*) AS row_count
FROM PIPELINE_MONITORING.DQ_PROJECT.GOLD_DQ_RESULTS;
SELECT COUNT(*) AS row_count
FROM PIPELINE_MONITORING.DQ_PROJECT.GOLD_FRESHNESS;

